# Индивидуальное задание №1.
Создать ноутбук, в котором будут приведены собственные примеры на языке Python для каждого из представленных свойств матричных вы-числений.

In [1]:
import numpy as np

Свойство 1. Дважды транспонированная матрица равна исходной матрице:

In [2]:
A = np.matrix('4 5 6 7; 2 1 3 3; 1 1 1 1')
print(A)

[[4 5 6 7]
 [2 1 3 3]
 [1 1 1 1]]


In [3]:
R = (A.T).T
print(R)

[[4 5 6 7]
 [2 1 3 3]
 [1 1 1 1]]


Свойство 2. Транспонирование суммы матриц равно сумме транспонированных матриц:

In [4]:
A = np.matrix('1 1 1 1; 2 1 3 3; 8 8 9 1')
B = np.matrix('4 5 6 7; 2 1 3 3; 8 8 9 1')
L = (A + B).T
R = A.T + B.T
print(L)

[[ 5  4 16]
 [ 6  2 16]
 [ 7  6 18]
 [ 8  6  2]]


In [5]:
print(R)

[[ 5  4 16]
 [ 6  2 16]
 [ 7  6 18]
 [ 8  6  2]]


Свойство 3. Транспонирование произведения матриц равно произведению транспонированных
матриц расставленных в обратном порядке:

In [9]:
A = np.matrix('1 1 1; 2 1 3; 8 9 1')
B = np.matrix('4 5 6; 2 1 3; 8 9 1')
L = (A.dot(B)).T
print('Транспонирование произведения матриц: \n', L)

Транспонирование произведения матриц: 
 [[14 34 58]
 [15 38 58]
 [10 18 76]]


In [11]:
R = (A.T).dot(B.T)
print('Произведение транспонированных матриц: \n', R)

Произведение транспонированных матриц: 
 [[62 28 34]
 [63 30 26]
 [25  8 36]]


Свойство 4. Транспонирование произведения матрицы на число равно произведению этого
числа на транспонированную матрицу:

In [12]:
A = np.matrix('4 4 4; 6 6 6; 8 8 8')
k = 2
L = (k * A).T
print('Транспонирования произведения матриц:\n', L)

Транспонирования произведения матриц:
 [[ 8 12 16]
 [ 8 12 16]
 [ 8 12 16]]


In [13]:
R = k * (A.T) 
print('Произведение числа на транспонированную матрицу\n', R)

Произведение числа на транспонированную матрицу
 [[ 8 12 16]
 [ 8 12 16]
 [ 8 12 16]]


Свойство 5*. Определители исходной и транспонированной матрицы совпадают:

In [14]:
A = np.matrix('7 2 4; 6 3 2; 9 5 7')
A_det = np.linalg.det(A)
A_T_det = np.linalg.det(A.T)
print(format(A_det, '.9g'))

41


In [15]:
print(format(A_T_det, '.9g'))

41


# Действия над матрицами 

Свойство 1. Произведение единицы и любой заданной матрицы равно заданной матрице:

In [16]:
A = np.matrix('7 2 4; 6 3 2; 9 5 7')
L = 1 * A
R = A
print(L)

[[7 2 4]
 [6 3 2]
 [9 5 7]]


In [17]:
print(R)

[[7 2 4]
 [6 3 2]
 [9 5 7]]


Свойство 2. Произведение нуля и любой матрицы равно нулевой матрице, размерность которой
равна исходной матрицы:

In [21]:
A = np.matrix('7 2 4; 6 3 2; 9 5 7')
L = 0 * A
Z = np.matrix('0 0 0; 0 0 0; 0 0 0')
R = Z
print(L)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [22]:
print(R)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


Свойство 3. Произведение матрицы на сумму чисел равно сумме произведений матрицы на
каждое из этих чисел:

In [24]:
A = np.matrix('7 2 4; 6 3 2; 9 5 7')
z = 2
v = 3
L = A * (z + v)
R = z * A + v * A
print('Произведение матрицы на сумму чисел \n', L)

Произведение матрицы на сумму чисел 
 [[35 10 20]
 [30 15 10]
 [45 25 35]]


In [25]:
print('Сумма произведений матрицы на 1 и 2 число \n', R)

Сумма произведений матрицы на 1 и 2 число 
 [[35 10 20]
 [30 15 10]
 [45 25 35]]


Свойство 4. Произведение матрицы на произведение двух чисел равно произведению второго
числа и заданной матрицы, умноженному на первое число:


In [26]:
A = np.matrix('7 2 4; 6 3 2; 9 5 7')
z = 2
v = 3
L = A * (z * v)
R = z * (v * A)
print('Произведение матрицы на произведение двух чисел \n', L)

Произведение матрицы на произведение двух чисел 
 [[42 12 24]
 [36 18 12]
 [54 30 42]]


In [27]:
print('Произведение второго числа на матрицу, умноженное на 1 число \n', R)

Произведение второго числа на матрицу, умноженное на 1 число 
 [[42 12 24]
 [36 18 12]
 [54 30 42]]


Свойство 5. Произведение суммы матриц на число равно сумме произведений этих матриц на
заданное число:

In [28]:
A = np.matrix('7 2 4; 6 3 2; 9 5 7')
B = np.matrix('1 2 3; 2 3 2; 2 3 3')
v = 3
L = v * (A + B)
R = v * A + B * v
print('Произведение суммы матриц на число \n', L)

Произведение суммы матриц на число 
 [[24 12 21]
 [24 18 12]
 [33 24 30]]


In [29]:
print('Сумма произведений матриц на число \n', R)

Сумма произведений матриц на число 
 [[24 12 21]
 [24 18 12]
 [33 24 30]]


# Сложение матриц

Свойство 1. Коммутативность сложения. От перестановки матриц их сумма не изменяется:

In [30]:
A = np.matrix('7 2 4; 6 3 2; 9 5 7')
B = np.matrix('1 2 3; 2 3 2; 2 3 3')
L = A + B
R = B + A
print('Сложение первой и второй матрицы: \n', L)

Сложение первой и второй матрицы: 
 [[ 8  4  7]
 [ 8  6  4]
 [11  8 10]]


In [31]:
print('Сложение второй и первой матрицы: \n', R)

Сложение второй и первой матрицы: 
 [[ 8  4  7]
 [ 8  6  4]
 [11  8 10]]


Свойство 2. Ассоциативность сложения. Результат сложения трех и более матриц не зависит от
порядка, в котором эта операция будет выполняться:

In [32]:
A = np.matrix('7 2 4; 6 3 2; 9 5 7')
B = np.matrix('1 2 3; 2 3 2; 2 3 3')
C = np.matrix('2 2 2; 4 5 3; 2 1 3')
L = (A + B) + C
R = B + (A + C)
print('К сумме первой и второй матриц, прибавляем третью \n', L)

К сумме первой и второй матриц, прибавляем третью 
 [[10  6  9]
 [12 11  7]
 [13  9 13]]


In [34]:
print('Ко второй матрице прибавляем сумму первой и третьей матрицы \n', L)

Ко второй матрице прибавляем сумму первой и третьей матрицы 
 [[10  6  9]
 [12 11  7]
 [13  9 13]]


Свойство 3. Для любой матрицы существует противоположная ей , такая, что их сумма является
нулевой матрицей :

In [42]:
A = np.matrix('7 2 4; 6 3 2; 9 5 7')
L = A + (-1) * A
Z = np.zeros((3,3))
print(L)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [43]:
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Умножение матриц

Свойство 1. Ассоциативность умножения. Результат умножения матриц не зависит от порядка, в
котором будет выполняться эта операция:

In [48]:
A = np.matrix('7 2 4; 6 3 2; 9 5 7')
B = np.matrix('1 2 3; 2 3 2; 2 3 3')
C = np.matrix('2 2 2; 4 5 3; 2 1 3')
L = (A.dot(B)).dot(C)
print('Произведение первой и второй матриц умноженное на третью \n', L)

Произведение первой и второй матриц умноженное на третью 
 [[240 235 245]
 [200 197 203]
 [398 394 402]]


In [50]:
R = A.dot(B.dot(C))
print('Умножение 1 матрицы на произведение 2 и 3 \n', R)

Умножение 1 матрицы на произведение 2 и 3 
 [[240 235 245]
 [200 197 203]
 [398 394 402]]


Свойство 2. Дистрибутивность умножения. Произведение матрицы на сумму матриц равно
сумме произведений матриц:

In [53]:
L = A.dot(B + C)
R = A.dot(B) + A.dot(C)
print('Произведение матрицы на сумму матриц \n', L)

Произведение матрицы на сумму матриц 
 [[ 49  60  69]
 [ 44  56  57]
 [ 85 104 112]]


In [54]:
print('Произведение матрицы на сумму матриц \n', R)

Произведение матрицы на сумму матриц 
 [[ 49  60  69]
 [ 44  56  57]
 [ 85 104 112]]


Свойство 3. Умножение матриц в общем виде не коммутативно. Это означает, что для матриц не
выполняется правило независимости произведения от перестановки множителей:

In [55]:
L = A.dot(B)
R = B.dot(A)
print(L)

[[19 32 37]
 [16 27 30]
 [33 54 58]]


In [56]:
print(R)

[[46 23 29]
 [50 23 28]
 [59 28 35]]


Свойство 4. Произведение заданной матрицы на единичную равно исходной матрице:

In [57]:
A = np.matrix('1 2 6; 2 3 4; 6 7 8')
E = np.matrix('1 0 0; 0 1 0; 0 0 1')
L = E.dot(A)
R = A.dot(E)
print('Произведение заданной матрицы на единичную равно исходной матрице \n', L)

Произведение заданной матрицы на единичную равно исходной матрице 
 [[1 2 6]
 [2 3 4]
 [6 7 8]]


In [58]:
print('Произведение заданной матрицы на единичную равно исходной матрице \n', R)

Произведение заданной матрицы на единичную равно исходной матрице 
 [[1 2 6]
 [2 3 4]
 [6 7 8]]


Свойство 5. Произведение заданной матрицы на нулевую матрицу равно нулевой матрице:

In [59]:
A = np.matrix('1 2 3; 3 4 5; 6 7 8')
Z = np.zeros((3, 3))
L = Z.dot(A)
R = A.dot(Z)
print(L)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [60]:
print(R)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Свойства определителя матрицы

In [65]:
A = np.matrix('7 2 4; 6 3 2; 9 5 7')
A_OP = np.linalg.det(A)
A_T = A.T
A_T_OP = np.linalg.det(A_T)
print(A)

[[7 2 4]
 [6 3 2]
 [9 5 7]]


In [66]:
print(A.T)

[[7 6 9]
 [2 3 5]
 [4 2 7]]


In [67]:
print(A_OP)

41.00000000000001


In [68]:
print(A_T_OP)

41.00000000000001


Свойство 2. Если у матрицы есть строка или столбец, состоящие из нулей, то определитель
такой матрицы равен нулю:

In [70]:
A = np.matrix('0 0 0; 6 3 2; 9 5 7')
Det_A = np.linalg.det(A)
print(A)

[[0 0 0]
 [6 3 2]
 [9 5 7]]


In [71]:
print('Определитель: ', Det_A)

Определитель:  0.0


Свойство 3. При перестановке строк матрицы знак ее определителя меняется на
противоположный:

In [72]:
A = np.matrix('7 2 4; 6 3 2; 9 5 7')
B = np.matrix('6 3 2; 7 2 4; 9 5 7')
Det_A = np.linalg.det(A)
Det_B = np.linalg.det(B)
print(Det_A)

41.00000000000001


In [73]:
print(Det_B)

-41.00000000000001


Свойство 4. Если у матрицы есть две одинаковые строки, то ее определитель равен нулю:

In [75]:
A = np.matrix('7 2 4; 7 2 4; 9 5 7')
Det_A = np.linalg.det(A)
print(Det_A)

0.0


Свойство 5. Если все элементы строки или столбца матрицы умножить на какое-то число, то и
определитель будет умножен на это число:

In [76]:
A = np.matrix('7 2 4; 6 3 2; 9 5 7')
print(A)

[[7 2 4]
 [6 3 2]
 [9 5 7]]


In [81]:
k = 4
B = A.copy()
B[0, :] = k * B[0, :]
print(B)

[[28  8 16]
 [ 6  3  2]
 [ 9  5  7]]


In [82]:
Det_B = np.linalg.det(B)
print(Det_B)

164.00000000000006


In [83]:
Det_A = np.linalg.det(A) * k
print(Det_A)

164.00000000000003


Свойство 6. Если все элементы строки или столбца можно представить как сумму двух
слагаемых, то определитель такой матрицы равен сумме определителей двух соответствующих
матриц:

In [89]:
A = np.matrix('7 2 4; 7 2 4; 9 5 7')
B = np.matrix('7 2 4; 2 3 2; 9 5 7')
C = A.copy()
C[1, :] += B[1, :]
print(C)

[[7 2 4]
 [9 5 6]
 [9 5 7]]


In [90]:
print(A)

[[7 2 4]
 [7 2 4]
 [9 5 7]]


In [91]:
print(B)

[[7 2 4]
 [2 3 2]
 [9 5 7]]


In [92]:
np.linalg.det(C)

17.0

In [93]:
np.linalg.det(A) + np.linalg.det(B)

16.999999999999986

Свойство 7. Если к элементам одной строки прибавить элементы другой строки, умноженные на
одно и тоже число, то определитель матрицы не изменится:


In [94]:
A = np.matrix('7 2 4; 7 2 4; 9 5 7')
k = 4
B = A.copy()
B[1, :] = B[1, :] + k * B[0, :]
print(A)

[[7 2 4]
 [7 2 4]
 [9 5 7]]


In [95]:
print(B)

[[ 7  2  4]
 [35 10 20]
 [ 9  5  7]]


In [99]:
round(np.linalg.det(A), 3)

0.0

In [100]:
round(np.linalg.det(B), 3)

0.0

Свойство 8. Если строка или столбец матрицы является линейной комбинацией других строк
(столбцов), то определитель такой матрицы равен нулю:

In [102]:
A = np.matrix('9 5 7; 10 4 -1; 7 2 4')
print(A)

[[ 9  5  7]
 [10  4 -1]
 [ 7  2  4]]


In [103]:
k = 4
A[1, :] = A[0, :] + k * A[2, :]
round(np.linalg.det(A), 3)

0.0

Свойство 9. Если матрица содержит пропорциональные строки, то ее определитель равен нулю:

In [104]:
A = np.matrix('-4 -1 2; 10 4 -1; 7 2 4')
print(A)

[[-4 -1  2]
 [10  4 -1]
 [ 7  2  4]]


In [105]:
k = 4
A[1, :] = k * A[0, :]
print(A)

[[ -4  -1   2]
 [-16  -4   8]
 [  7   2   4]]


In [106]:
round(np.linalg.det(A), 3)

0.0

# Рассмотрим свойства обратной матрицы.
Свойство 1. Обратная матрица обратной матрицы есть исходная матрица:

In [109]:
A = np.matrix('-4 -1 2; 10 4 -1; 9 5 7')
A_inv = np.linalg.inv(A)
A_inv_inv = np.linalg.inv(A_inv)
print(A)

[[-4 -1  2]
 [10  4 -1]
 [ 9  5  7]]


In [110]:
print(A_inv_inv)

[[-4. -1.  2.]
 [10.  4. -1.]
 [ 9.  5.  7.]]


Свойство 2. Обратная матрица транспонированной матрицы равна транспонированной матрице
от обратной матрицы:

In [113]:
A = np.matrix('1 -3 5; 10 4 -1; 9 5 7')
L = np.linalg.inv(A.T)
R = (np.linalg.inv(A)).T
print(L)

[[ 0.09705882 -0.23235294  0.04117647]
 [ 0.13529412 -0.11176471 -0.09411765]
 [-0.05        0.15        0.1       ]]


In [114]:
print(R)

[[ 0.09705882 -0.23235294  0.04117647]
 [ 0.13529412 -0.11176471 -0.09411765]
 [-0.05        0.15        0.1       ]]


Свойство 3. Обратная матрица произведения матриц равна произведению обратных матриц:

In [117]:
A = np.matrix('1 2 3; 7 2 4; 9 5 7')
B = np.matrix('7 2 4; 2 3 2; 8 8 5')
L = np.linalg.inv(A.dot(B))
R = np.linalg.inv(B).dot(np.linalg.inv(A))
print(L)

[[ 0.81091618  1.06237817 -0.9122807 ]
 [ 0.34502924  0.25730994 -0.26315789]
 [-1.6705653  -1.97465887  1.75438596]]


In [118]:
 print(R)

[[ 0.81091618  1.06237817 -0.9122807 ]
 [ 0.34502924  0.25730994 -0.26315789]
 [-1.6705653  -1.97465887  1.75438596]]
