# Создать ноутбук, в котором будут приведены собственные примеры ре-шения систем линейных уравнений матричным методом и методом Кра-мера. 

## Метод Крамера

Рассмотрим систему из $n$ уравнений с $n$ неизвестными.<br> Если $\triangle \ne 0$, то система имеет единственное решение, которое может быть определенне по формулам Крамера $x_1 = \frac{\triangle_1}{\triangle};  x_2 = \frac{\triangle_2}{\triangle}; x_3 = \frac{\triangle_3}{\triangle}$ 

Создадим и заполним матрицу:

In [1]:
import numpy as np

In [2]:
# Заполняем матрицу рандомными значениями от 0 до 20
matrix = np.random.randint (0, 20, (4, 4))
print(matrix)

[[17  7 19 15]
 [17  5 11 13]
 [ 3 18  5  3]
 [ 9 11  7 10]]


In [3]:
# Ищем определитель
op1 = np.linalg.det(matrix)
print(op1)

6344.0000000000055


In [4]:
# Заполняем рандомными значенями столбец свободных членов
svobod = np.random.randint (0, 20, (4, 1))
print(svobod)
x = np.ones((4, 1))

[[ 9]
 [ 6]
 [17]
 [ 5]]


Найдем определитель и дополнительные определители, а также решения по формулам Крамера

In [6]:
# Решаем матрицу методом крамера
t = [1, 2, 3, 4]
if op1 != 0:
    for i in t:
        # Копируем значения в дополнительную матрицу
        matrix_dop = matrix.copy()
        # Подставляем столбец свободных членов в дополнительную матрицу
        matrix_dop[:, i] = svobod[:, t]
        # Считаем определители и выводим решения СЛАУ
        x[i,t] = np.linalg.det(matrix_dop) / op1
    print(x)
else:
    print("Матрица вырожденная, нельзя продолжить.")

IndexError: index 1 is out of bounds for axis 1 with size 1

## Матричный метод:

Пусть дана система $n$ линейных уравнений с $n$ переменными $(n \times n)$.<br> Если основная матрица не вырождена, т.е. $\vert A \vert \ne 0$, тогда для матрицы $А$ существует $А^{-1}$. Умножив матричное уравнение на $А^{-1}$ получим: $$X = А^{-1} * B$$

Создадим и заполним матрицу:

In [7]:
# Заполняем матрицу рандомными значениями
matrix = np.random.randint (0, 20, (4, 4))
print(matrix)

[[ 5 15  5 15]
 [19  8  2  7]
 [ 1 11  4 19]
 [16 17  4  1]]


Найдем определитель $\vert A \vert$, обратную матрицу $А^{-1} = E / A$ и присоединенную $A^*$.

In [8]:
# Для решения матричным методом необходимо найти обратную матрицу:
matrix_inv = np.linalg.inv(matrix)
print(matrix_inv)

[[ 0.0776699   0.0776699  -0.08737864 -0.04854369]
 [-0.76504854 -0.16504854  0.64401294  0.39482201]
 [ 2.98834951  0.38834951 -2.4368932  -1.24271845]
 [-0.19029126  0.00970874  0.197411    0.03559871]]


In [9]:
# находим определитель матрциы
op1 = np.linalg.det(matrix)
print(op1)

-1544.9999999999995


In [10]:
# Заполняем столбец свободных членов (B)
svobod = np.random.randint (0, 20, (4, 1))
print(svobod)

[[10]
 [ 1]
 [ 5]
 [ 8]]


Найдём решения СЛАУ:

In [11]:
# Умножаем нашу обратную матрицу на столбец свободных членов и получаем решение СЛАУ
if op1 != 0:
    x = matrix_inv.dot(svobod)
    print(x)
else: 
    print("Невозможно решить, т.к определитель матрицы равен 0")

[[ 0.02912621]
 [-1.4368932 ]
 [ 8.14563107]
 [-0.62135922]]


Найденные решения