# Создать ноутбук, в котором будут приведены собственные примеры ре-шения систем линейных уравнений матричным методом и методом Кра-мера. 

## Метод Крамера

Рассмотрим систему из $n$ уравнений с $n$ неизвестными.<br> Если $\triangle \ne 0$, то система имеет единственное решение, которое может быть определенне по формулам Крамера $x_1 = \frac{\triangle_1}{\triangle};  x_2 = \frac{\triangle_2}{\triangle}; x_3 = \frac{\triangle_3}{\triangle}$ 

Создадим и заполним матрицу:

In [60]:
import numpy as np

In [61]:
# Заполняем матрицу рандомными значениями от 0 до 20
matrix = np.random.randint (0, 20, (4, 4))
print(matrix)

[[ 4  0 12 12]
 [ 6 18  3 13]
 [ 8  3  6  9]
 [ 0 18  1  5]]


In [62]:
# Ищем определитель
op1 = np.linalg.det(matrix)
print(op1)

5159.999999999992


In [63]:
# Заполняем рандомными значенями столбец свободных членов
svobod = np.random.randint (0, 20, (4, 1))
print(svobod)
x = np.ones((4, 1))

[[16]
 [ 7]
 [ 7]
 [14]]


Найдем определитель и дополнительные определители, а также решения по формулам Крамера

In [64]:
# Решаем матрицу методом крамера
if op1 != 0:
    for i in range(4):
        # Копируем значения в дополнительную матрицу
        matrix_dop = matrix.copy()
        # Подставляем столбец свободных членов в дополнительную матрицу
        matrix_dop[:, i] = svobod[:, 0]
        # Считаем определители и выводим решения СЛАУ
        x[i,0] = np.linalg.det(matrix_dop) / op1
    print(x)
else:
    print("Матрица вырожденная, нельзя продолжить.")

[[ 0.1627907 ]
 [ 1.09689922]
 [ 3.03488372]
 [-1.75581395]]


## Матричный метод:

Пусть дана система $n$ линейных уравнений с $n$ переменными $(n \times n)$.<br> Если основная матрица не вырождена, т.е. $\vert A \vert \ne 0$, тогда для матрицы $А$ существует $А^{-1}$. Умножив матричное уравнение на $А^{-1}$ получим: $$X = А^{-1} * B$$

Создадим и заполним матрицу:

In [43]:
# Заполняем матрицу рандомными значениями
matrix = np.random.randint (0, 20, (4, 4))
print(matrix)

[[17 19 14  3]
 [ 1  6 15 18]
 [ 8  4 12 15]
 [16  1  4  5]]


Найдем определитель $\vert A \vert$, обратную матрицу $А^{-1} = E / A$ и присоединенную $A^*$.

In [47]:
# Для решения матричным методом необходимо найти обратную матрицу:
matrix_inv = np.linalg.inv(matrix)
print(matrix_inv)

[[-5.45454545e-02  1.05454545e+00 -1.52727273e+00  8.18181818e-01]
 [-2.18181818e+00  4.21818182e+01 -6.00909091e+01  2.97272727e+01]
 [ 3.58181818e+00 -6.75818182e+01  9.62909091e+01 -4.77272727e+01]
 [-2.25454545e+00  4.22545455e+01 -6.01272727e+01  2.98181818e+01]]


In [50]:
# Заполняем столбец свободных членов (B)
op1 = np.linalg.det(matrix)
print(op1)

55.00000000000119


svobod = np.random.randint (0, 20, (4, 1))
print(svobod)

Найдём решения СЛАУ:

In [53]:
# Умножаем нашу обратную матрицу на столбец свободных членов и получаем решение СЛАУ
if op1 != 0:
    x = matrix_inv.dot(svobod)
    print(x)
else: 
    print("Невозможно решить, т.к определитель матрицы равен 0")

[[  12.29090909]
 [ 465.63636364]
 [-745.43636364]
 [ 465.69090909]]


Найденные решения